### ISSUE TITLE
need we update "clades.tsv" file if new clades are classified?

### ISSUE THREAD

**Issue by liamxg** [nextstrain/nextstrain-walkthrough#3]

**Comment by huddlej** [comment]
Hi @liamxg, yes, when new clades get defined, you need to update the clades TSV file accordingly and re-run the workflow to reflect that change.

**Comment by liamxg** [comment]
@huddlej  if there are new clades that are not listed in "clades.tsv" file, how should I do ?

**Comment by huddlej** [comment]
@liamxg If you want the latest SARS-CoV-2 clades, then you can follow [the ncov workflow change log](https://docs.nextstrain.org/projects/ncov/en/latest/reference/change_log.html) to see when new clades get mentioned. You can also check for updates to [the emerging lineages file](https://github.com/nextstrain/ncov/blob/master/defaults/emerging_lineages.tsv) (which is in the same format as the clades.tsv in this repo) or [the Nextstrain clades file](https://github.com/nextstrain/ncov/blob/master/defaults/clades.tsv).

**Comment by liamxg** [comment]
thanks.
